SELECT c.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR c
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h ON h.CAR_ID = c.CAR_ID
WHERE c.CAR_TYPE = '세단' and MONTH(h.START_DATE) = 10
GROUP BY c.CAR_ID
ORDER BY c.CAR_ID DESC
