SELECT r.FOOD_TYPE, r.REST_ID, r.REST_NAME, r.FAVORITES
FROM REST_INFO r
JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS max_favorites
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) AS sub
ON r.FOOD_TYPE = sub.FOOD_TYPE AND r.FAVORITES = sub.max_favorites
ORDER BY r.FOOD_TYPE DESC;
